# Simple workflow for deploying selected static content to GitHub Pages
name: Deploy static content to Pages

on:
  push:
    branches: ["main"]       # Trigger on push to main branch
  workflow_dispatch:          # Manual trigger option

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout repository
      - name: Checkout
        uses: actions/checkout@v4

      # 2️⃣ Setup GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # 3️⃣ Prepare only the files we want
      - name: Prepare files for deployment
        run: |
          mkdir deploy
          cp index_original.html deploy/index.html
          cp app.js deploy/
          cp -r enhanced_styles deploy/

      # 4️⃣ Upload artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: deploy

      # 5️⃣ Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
